###############################################################
#                                                             #
#      Kitty DotFiles configuration for Hyprland              #
#                                                             #
###############################################################

font_family      IosevkaTerm Nerd Font
font_size 12
# cursor #ad8ee6
cursor_shape block

#: The cursor shape can be one of block, beam, underline. Note that
cursor_beam_thickness 1.5
background_opacity 0.95
window_padding_width 8



# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
